package Laporan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import Koneksi.GlobalVar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Doni Hadimas
 */
public class Laporan extends javax.swing.JFrame {
  DefaultTableModel table = new DefaultTableModel();
    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        
        tabel_penjualan.setModel(table);
        table.addColumn("no_penjualan");
        table.addColumn("tanggal_penjualan");
        table.addColumn("username");
        table.addColumn("total");

        tampilData();
        combo_caribulan();
        combo_caritahun();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penjualan = new javax.swing.JTable();
        BtnCari = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        cmb_caribulan = new javax.swing.JComboBox<>();
        cmb_caritahun = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_totalpemasukan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/activity [#985].png"))); // NOI18N
        jLabel1.setText("LAPORAN");
        jLabel1.setIconTextGap(20);

        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penjualan);

        BtnCari.setBackground(new java.awt.Color(41, 39, 40));
        BtnCari.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnCari.setForeground(new java.awt.Color(255, 255, 255));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/search_left [#1504].png"))); // NOI18N
        BtnCari.setBorder(null);
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });

        BtnKembali.setBackground(new java.awt.Color(41, 39, 40));
        BtnKembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnKembali.setForeground(new java.awt.Color(255, 255, 255));
        BtnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/arrow_left [#335].png"))); // NOI18N
        BtnKembali.setText("Kembali Ke Menu Admin");
        BtnKembali.setBorder(null);
        BtnKembali.setBorderPainted(false);
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        cmb_caribulan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmb_caribulanComponentShown(evt);
            }
        });
        cmb_caribulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_caribulanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Pemasukan : RP.");

        txt_totalpemasukan.setEditable(false);
        txt_totalpemasukan.setBackground(new java.awt.Color(41, 39, 40));
        txt_totalpemasukan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txt_totalpemasukan.setForeground(new java.awt.Color(255, 255, 255));
        txt_totalpemasukan.setBorder(null);
        txt_totalpemasukan.setCaretColor(new java.awt.Color(41, 39, 40));
        txt_totalpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalpemasukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_caribulan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_caritahun, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_totalpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_caribulan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_caritahun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 60, Short.MAX_VALUE)
                        .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_totalpemasukan))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        // TODO add your handling code here:
        Admin.MenuAdmin frm = new Admin.MenuAdmin();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void tabel_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penjualanMouseClicked
        // TODO add your handling code here:
        int baris_tb = tabel_penjualan.getSelectedRow(); //mengambil indeks row pada kolom yang dipilih
        GlobalVar.no_pen = table.getValueAt(baris_tb,0).toString();
        Detail_Lap.detail_laporan tampil = new Detail_Lap.detail_laporan();
        tampil.setVisible(true);
    }//GEN-LAST:event_tabel_penjualanMouseClicked

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        // TODO add your handling code here
        cari();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void cmb_caribulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_caribulanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_caribulanActionPerformed

    private void cmb_caribulanComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmb_caribulanComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_caribulanComponentShown

    private void txt_totalpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalpemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalpemasukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }
    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = tabel_penjualan.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = "SELECT t_penjualan.no_penjualan,tanggal_penjualan,username,sum(total)AS Total FROM t_penjualan INNER JOIN t_users ON t_penjualan.id_user = t_users.id_user INNER JOIN t_det_penjualan ON t_penjualan.no_penjualan = t_det_penjualan.no_penjualan GROUP BY t_penjualan.no_penjualan";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            int total_pemasukan = 0;
            while (rslt.next()){
                //menampung data sementara
                   
                    String no_penjualan = rslt.getString("no_penjualan");
                    String tanggal_penjualan = rslt.getString("tanggal_penjualan");
                    String username = rslt.getString("username");
                    String total = rslt.getString("Total");
                    
                //masukan semua data kedalam array
                String[] data = {no_penjualan, tanggal_penjualan, username, total};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
                int rowcount = tabel_penjualan.getRowCount();
                if(rowcount != 0){
                    for (int i = 0; i< rowcount; i++){
                        String a = tabel_penjualan.getValueAt(i, 3).toString();
                        total_pemasukan = total_pemasukan + Integer.parseInt(a);
                    }
                    txt_totalpemasukan.setText(String.valueOf(total_pemasukan));
                    total_pemasukan = 0;
                }else{
                    total_pemasukan = 0;
                }
            }
                //mengeset nilai yang ditampung agar muncul di table
                tabel_penjualan.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void cari(){
        int row = tabel_penjualan.getRowCount();
//        String bln = "";
        String thn, bln;
             
        int bulan = cmb_caribulan.getSelectedIndex();
        thn = cmb_caritahun.getSelectedItem().toString();
        bln = String.valueOf(bulan);
         for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = "SELECT t_penjualan.no_penjualan, tanggal_penjualan, username, sum(total)AS Total FROM t_penjualan INNER JOIN t_users ON t_penjualan.id_user = t_users.id_user INNER JOIN t_det_penjualan ON t_penjualan.no_penjualan = t_det_penjualan.no_penjualan WHERE `tanggal_penjualan` BETWEEN '" +thn+ "-" +bln+ "-01' AND '" +thn+ "-" +bln+ "-30' GROUP BY t_penjualan.no_penjualan";
                
       try{
           Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           int total_pemasukan = 0;
           while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("no_penjualan");
                    String tgl = rslt.getString("tanggal_penjualan");
                    String user = rslt.getString("username");
                    String ttl = rslt.getString("Total");
                    
                    
                //masukan semua data kedalam array
                String[] data = {kode,tgl,user,ttl};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tabel_penjualan.setModel(table);
           
        
    }catch(Exception e){
           System.out.println(e);
    }
    }
    private void combo_caribulan(){
        cmb_caribulan.addItem("Bulan");
        cmb_caribulan.addItem("Januari");
        cmb_caribulan.addItem("Februari");
        cmb_caribulan.addItem("Maret");
        cmb_caribulan.addItem("April");
        cmb_caribulan.addItem("Mei");
        cmb_caribulan.addItem("Juni");
        cmb_caribulan.addItem("Juli");
        cmb_caribulan.addItem("Agustus");
        cmb_caribulan.addItem("September");
        cmb_caribulan.addItem("Oktober");
        cmb_caribulan.addItem("November");
        cmb_caribulan.addItem("Desember");
    }
    
    private void combo_caritahun(){
        cmb_caritahun.addItem("Tahun");
        for(int thn = 2010; thn <= 2050; thn++ ){
            cmb_caritahun.addItem("" + thn);
        }
    }
    private void total_pemasukan(){
        String bln = String.valueOf(cmb_caribulan.getSelectedIndex());
        String thn = String.valueOf(cmb_caritahun.getSelectedItem().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JComboBox<String> cmb_caribulan;
    private javax.swing.JComboBox<String> cmb_caritahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_penjualan;
    private javax.swing.JTextField txt_totalpemasukan;
    // End of variables declaration//GEN-END:variables
}
