/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Koneksi.GlobalVar;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Nurul Kafi
 */
public class Form_Transaksi extends javax.swing.JFrame {
    DefaultTableModel table = new DefaultTableModel();
    DefaultTableModel table2 = new DefaultTableModel();
    /**
     * Creates new form Form_Transaksi
     */
    public Form_Transaksi() {
        initComponents();
        
        tabel_keranjang.setModel(table);
        table.addColumn("Kode");
        table.addColumn("Nama");
        table.addColumn("Harga");
        table.addColumn("QTY");
        table.addColumn("Total");
        konci.setVisible(false);
        tabel_barang.setModel(table2);
        table2.addColumn("Kode");
        table2.addColumn("Nama");
        table2.addColumn("Jenis");
        table2.addColumn("Harga");
        table2.addColumn("Stock");
        kodeotomatis();
        
        txt_namabarang.setText(GlobalVar.namabarang);
        txt_harga_barang.setText(GlobalVar.harga);
        txt_koderansaksi.enable(false);
        txt_namabarang.enable(false);
        txt_harga_barang.enable(false);
        lblTotal.setText(String.valueOf(0));
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        BtnSimpan.setVisible(false);
    }
    
     
    private void kodeotomatis(){
        Date tanggal = new Date();
        SimpleDateFormat s =new SimpleDateFormat("ddMMyyyy");
        String tgl = s.format(tanggal);
        String query = "SELECT * FROM `t_penjualan` ORDER BY time DESC ";
        String kodeotomatis;
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String no_penjualan = rslt.getString("no_penjualan").substring(9,12);
                String AN = "" + (Integer.parseInt(no_penjualan)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                txt_koderansaksi.setText(tgl + NOL + AN);
            }else{
                txt_koderansaksi.setText(tgl +"0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        konci = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_keranjang = new javax.swing.JTable();
        txt_qty = new javax.swing.JTextField();
        txt_koderansaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_harga_barang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnKeranjang = new javax.swing.JButton();
        BtnTmbhKeranjang = new javax.swing.JButton();
        BtnCari = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        txt_namabarang = new javax.swing.JTextField();
        txt_totalbayar1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnProses = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblkembalian = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_barang);

        konci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(konci, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 39, 40));

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/money_round [#1184].png"))); // NOI18N
        jLabel1.setText("TRANSAKSI");
        jLabel1.setIconTextGap(20);

        tabel_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_keranjangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_keranjang);

        txt_qty.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_qty.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_qtyInputMethodTextChanged(evt);
            }
        });

        txt_koderansaksi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_koderansaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/dollar [#1189].png"))); // NOI18N
        jLabel2.setText("Harga Barang");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/touch_id [#1377].png"))); // NOI18N
        jLabel3.setText("Kode Transaksi");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/drink [#46].png"))); // NOI18N
        jLabel5.setText("Nama Barang");

        txt_harga_barang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/number_sign [#110].png"))); // NOI18N
        jLabel6.setText("Qty");

        BtnKeranjang.setBackground(new java.awt.Color(41, 39, 40));
        BtnKeranjang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        BtnKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/cart_minus_round [#1162].png"))); // NOI18N
        BtnKeranjang.setBorder(null);
        BtnKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeranjangActionPerformed(evt);
            }
        });

        BtnTmbhKeranjang.setBackground(new java.awt.Color(41, 39, 40));
        BtnTmbhKeranjang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnTmbhKeranjang.setForeground(new java.awt.Color(255, 255, 255));
        BtnTmbhKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/cart_plus [#1157].png"))); // NOI18N
        BtnTmbhKeranjang.setText("Tambah");
        BtnTmbhKeranjang.setBorder(null);
        BtnTmbhKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTmbhKeranjangActionPerformed(evt);
            }
        });

        BtnCari.setBackground(new java.awt.Color(41, 39, 40));
        BtnCari.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnCari.setForeground(new java.awt.Color(255, 255, 255));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/cart_plus_round [#1158].png"))); // NOI18N
        BtnCari.setBorder(null);
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });

        BtnKembali.setBackground(new java.awt.Color(41, 39, 40));
        BtnKembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnKembali.setForeground(new java.awt.Color(255, 255, 255));
        BtnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/arrow_left [#334].png"))); // NOI18N
        BtnKembali.setText("Menu ");
        BtnKembali.setBorder(null);
        BtnKembali.setBorderPainted(false);
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        txt_namabarang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_namabarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_totalbayar1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_totalbayar1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_totalbayar1InputMethodTextChanged(evt);
            }
        });
        txt_totalbayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbayar1ActionPerformed(evt);
            }
        });
        txt_totalbayar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_totalbayar1KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/dollar [#1189].png"))); // NOI18N
        jLabel4.setText("Total Bayar");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/dollar [#1189].png"))); // NOI18N
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/dollar [#1189].png"))); // NOI18N
        jLabel8.setText("Kembalian");

        BtnProses.setBackground(new java.awt.Color(41, 39, 40));
        BtnProses.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnProses.setForeground(new java.awt.Color(255, 255, 255));
        BtnProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/record [#982].png"))); // NOI18N
        BtnProses.setText("Proses");
        BtnProses.setBorder(null);
        BtnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProsesActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");

        lblTotal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTotal1.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal1.setText("RP.");

        lblTotal2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTotal2.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal2.setText("RP.");

        lblkembalian.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblkembalian.setForeground(new java.awt.Color(255, 255, 255));
        lblkembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkembalian.setText("0");

        BtnSimpan.setBackground(new java.awt.Color(41, 39, 40));
        BtnSimpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/save_item [#1411].png"))); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.setBorder(null);
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnRefresh.setBackground(new java.awt.Color(41, 39, 40));
        BtnRefresh.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        BtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/arrow_repeat [#235].png"))); // NOI18N
        BtnRefresh.setText("Refresh");
        BtnRefresh.setBorder(null);
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_harga_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_koderansaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTmbhKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal)))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_totalbayar1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(BtnKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblkembalian))
                                    .addComponent(jLabel8))
                                .addGap(67, 67, 67)
                                .addComponent(BtnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotal1)
                            .addComponent(txt_totalbayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblkembalian)
                                    .addComponent(lblTotal2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_koderansaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_harga_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(BtnTmbhKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_keranjangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabel_keranjangMouseClicked
    private void clear(){
        txt_namabarang.setText(null);
        txt_qty.setText(null);
        txt_harga_barang.setText(null);
        lblTotal.setText("0");
        lblkembalian.setText("0");
        txt_totalbayar1.setText(null);
        int a  = tabel_keranjang.getRowCount();
        for(int i = a-1;i>=0;i--){
            table.removeRow(i);
        }
        kodeotomatis();
    }
    private void BtnKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeranjangActionPerformed
        // TODO add your handling code here:
        int baris = tabel_keranjang.getSelectedRow();
        
        String total = tabel_keranjang.getValueAt(baris, 4).toString();
        int a = Integer.parseInt(lblTotal.getText());
        int hasil = a - Integer.parseInt(total);
        table.removeRow(tabel_keranjang.getSelectedRow());
        lblTotal.setText(String.valueOf(hasil));
    
    }//GEN-LAST:event_BtnKeranjangActionPerformed

    private void BtnTmbhKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTmbhKeranjangActionPerformed
        // TODO add your handling code here:
        if(txt_qty.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI QTY!");
        }
        int total;
        int totalbayar;
        total = Integer.parseInt(txt_harga_barang.getText()) * Integer.parseInt(txt_qty.getText());
        totalbayar = total + Integer.parseInt(lblTotal.getText());
        table.addRow(new Object[]{Koneksi.GlobalVar.kode, txt_namabarang.getText(), txt_harga_barang.getText(),txt_qty.getText(),total});         
        lblTotal.setText(String.valueOf(totalbayar));
       
    }//GEN-LAST:event_BtnTmbhKeranjangActionPerformed
//    private void buattable(){
//    tabel_barang.setModel(table2);
//    table2.addColumn("Kode");
//        table2.addColumn("Nama");
//        table2.addColumn("Jenis");
//        table2.addColumn("Harga");
//        table2.addColumn("Stock");}
    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
            // TODO add your handling code here:
//        buattable();
        tampilData();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300, 300, 600, 400);
        konci.requestFocus();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        // TODO add your handling code here:
        Admin.MenuAdmin frm = new Admin.MenuAdmin();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void txt_qtyInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_qtyInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyInputMethodTextChanged

    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = tabel_barang.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = "SELECT * FROM t_barang";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("kode_barang");
                    String nama = rslt.getString("nama_barang");
                    String jenis = rslt.getString("jenis_barang");
                    String harga = rslt.getString("harga");
                    String stok = rslt.getString("stock");
                    
                //masukan semua data kedalam array
                String[] data = {kode,nama,jenis,harga,stok};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table2.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tabel_barang.setModel(table2);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        // TODO add your handling code here:
        
        int baris = tabel_barang.getSelectedRow();
        String kode = table2.getValueAt(baris,0).toString();
        Koneksi.GlobalVar.kode = kode;
        String nama = table2.getValueAt(baris,1).toString();
        Koneksi.GlobalVar.namabarang = nama;
        txt_namabarang.setText(nama);
        String harga = table2.getValueAt(baris, 3).toString();
        Koneksi.GlobalVar.harga = harga;
        txt_harga_barang.setText(harga);
        txt_qty.requestFocus(true);
        table2.getDataVector().removeAllElements();
        table2.fireTableDataChanged();
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void konciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konciActionPerformed

    private void txt_totalbayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbayar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalbayar1ActionPerformed

    private void txt_totalbayar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalbayar1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_totalbayar1KeyTyped

    private void txt_totalbayar1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_totalbayar1InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_totalbayar1InputMethodTextChanged

    private void BtnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProsesActionPerformed
        // TODO add your handling code here:
       int a,b,c,d;
       a = Integer.parseInt(lblTotal.getText());
       b = Integer.parseInt(txt_totalbayar1.getText());
       c = b - a; 
       lblkembalian.setText(String.valueOf(c));
       if(b<a){
           JOptionPane.showMessageDialog(null, "Uang Anda Kurang!");
       }else{
           BtnSimpan.setVisible(true);
       }
    }//GEN-LAST:event_BtnProsesActionPerformed
    private void simpan(){
        Connection connect = Koneksi.Koneksi.getKoneksi();
        Date tanggal = new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        String tgl = s.format(tanggal);
        int a = tabel_keranjang.getRowCount();
        String nota= txt_koderansaksi.getText();
            String query2 = "INSERT INTO `t_penjualan` (no_penjualan,tanggal_penjualan,id_user) "
                     + "VALUES ('"+nota+"','"+tgl+"', '"+GlobalVar.id_user+"')";
        
            try{
                //menyiapkan statement untuk di eksekusi
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                for(int i = 0; i<=a;i++ ){
                String kode = tabel_keranjang.getValueAt(i, 0).toString();
                String harga_jual = tabel_keranjang.getValueAt(i, 2).toString();
                String qty = tabel_keranjang.getValueAt(i, 3).toString();
                String total = tabel_keranjang.getValueAt(i, 4).toString();
    
                String query = "INSERT INTO `t_det_penjualan` (no_penjualan,kode_barang, harga_jual,qty, total) "
                         + "VALUES ('"+nota+"','"+kode+"', '"+harga_jual+"','"+qty+"', '"+total+"')";
                try{
                    //menyiapkan statement untuk di eksekusi
                    PreparedStatement ps2 = (PreparedStatement) connect.prepareStatement(query);
                    ps.executeUpdate(query);
                    JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                }catch(SQLException | HeadlessException e){
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
                }
                }
            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
            }
        
    }
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        simpan();
        
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        clear();
    }//GEN-LAST:event_BtnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnKeranjang;
    private javax.swing.JButton BtnProses;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTmbhKeranjang;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField konci;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblkembalian;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_keranjang;
    private javax.swing.JTextField txt_harga_barang;
    private javax.swing.JTextField txt_koderansaksi;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_totalbayar1;
    // End of variables declaration//GEN-END:variables
}
