/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pegawai;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alerio
 */
public class Pegawai extends javax.swing.JFrame {
    DefaultTableModel table = new DefaultTableModel();
    /**
     * Creates new form Pegawai
     */
    public Pegawai() {
        initComponents();
        
        txt_idpegawai.setVisible(false);
        kodeotomatis();
        Koneksi.Koneksi conn = new Koneksi.Koneksi();
        cb_jeniskelamin.addItem("Laki-Laki");
        cb_jeniskelamin.addItem("Perempuan");
        cb_pegawai.addItem("kasir");
        cb_pegawai.addItem("gudang");
        txt_idpegawai.setVisible(false);
        
        tabel_pegawai.setModel(table);
        table.addColumn("Id Pegawai");
        table.addColumn("Nama Pegawai");
        table.addColumn("Jenis Kelamin");
        table.addColumn("Jenis Pegawai");
        table.addColumn("Alamat");
        table.addColumn("No HP");
        tampilData();
    }
    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = tabel_pegawai.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = "SELECT * FROM `t_pegawai` ";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String id = rslt.getString("id_pegawai");
                    String nama = rslt.getString("nama_pegawai");
                    String jeniskel = rslt.getString("jenis_kelamin");
                    String jenis = rslt.getString("jenis_pegawai");
                    String alamat = rslt.getString("alamat");
                    String nohp = rslt.getString("no_hp");
                    
                //masukan semua data kedalam array
                String[] data = {id,nama,jeniskel,jenis,alamat,nohp};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tabel_pegawai.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idpegawai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pegawai = new javax.swing.JTable();
        txt_no_hp = new javax.swing.JTextField();
        txt_namapegawai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_jeniskelamin = new javax.swing.JComboBox<>();
        txt_alamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnBarang = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        BtnCari = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cb_pegawai = new javax.swing.JComboBox<>();

        txt_idpegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_idpegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/profile [#1339].png"))); // NOI18N
        jLabel1.setText("PEGAWAI");
        jLabel1.setIconTextGap(20);

        tabel_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pegawai);

        txt_no_hp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txt_namapegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_namapegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/home [#1391].png"))); // NOI18N
        jLabel2.setText("Alamat");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/profile [#1335].png"))); // NOI18N
        jLabel3.setText("Nama Pegawai");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/profile_image_favorite_round [#1330].png"))); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        cb_jeniskelamin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cb_jeniskelamin.setMaximumRowCount(2);

        txt_alamat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/phone [#226].png"))); // NOI18N
        jLabel6.setText("No HP");

        jButton1.setBackground(new java.awt.Color(41, 39, 40));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/delete [#1487].png"))); // NOI18N
        jButton1.setText("Hapus");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnBarang.setBackground(new java.awt.Color(41, 39, 40));
        BtnBarang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnBarang.setForeground(new java.awt.Color(255, 255, 255));
        BtnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/profile_image_plus [#1359].png"))); // NOI18N
        BtnBarang.setText("Tambah");
        BtnBarang.setBorder(null);
        BtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBarangActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(41, 39, 40));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/edit_cover [#1481].png"))); // NOI18N
        jButton3.setText("Ubah");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_cari.setToolTipText("Cari berdasarkan nama,jenis,harga, dan stock");

        BtnCari.setBackground(new java.awt.Color(41, 39, 40));
        BtnCari.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnCari.setForeground(new java.awt.Color(255, 255, 255));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/search_left [#1504].png"))); // NOI18N
        BtnCari.setBorder(null);
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });

        BtnKembali.setBackground(new java.awt.Color(41, 39, 40));
        BtnKembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnKembali.setForeground(new java.awt.Color(255, 255, 255));
        BtnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/arrow_left [#335].png"))); // NOI18N
        BtnKembali.setText("Kembali Ke Menu Admin");
        BtnKembali.setBorder(null);
        BtnKembali.setBorderPainted(false);
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/PNG@1_white_icons/profile [#1335].png"))); // NOI18N
        jLabel7.setText("Jenis Pegawai");

        cb_pegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cb_pegawai.setMaximumRowCount(2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGap(68, 68, 68))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(BtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(136, 136, 136))
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cb_jeniskelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_namapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_namapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cb_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        // TODO add your handling code here:
        Admin.MenuAdmin frm = new Admin.MenuAdmin();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        editData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBarangActionPerformed
        // TODO add your handling code here:
        tambahData();
    }//GEN-LAST:event_BtnBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabel_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pegawaiMouseClicked
        // TODO add your handling code here:
        BtnBarang.enable();
        int baris = tabel_pegawai.getSelectedRow();
        String kode = tabel_pegawai.getValueAt(baris,0).toString();
        txt_idpegawai.setText(kode);
        String nama = tabel_pegawai.getValueAt(baris,1).toString();
        txt_namapegawai.setText(nama);

        String jenis = tabel_pegawai.getValueAt(baris, 2).toString();
        cb_jeniskelamin.addItem(jenis);
        
        String jenis_pekerjaan = tabel_pegawai.getValueAt(baris, 3).toString();
        cb_pegawai.addItem(jenis_pekerjaan);

        String alamat = tabel_pegawai.getValueAt(baris, 4).toString();
        txt_alamat.setText(alamat);
        
        String no_hp = tabel_pegawai.getValueAt(baris, 5).toString();
        txt_no_hp.setText(no_hp);
        

        txt_idpegawai.setVisible(true);
    }//GEN-LAST:event_tabel_pegawaiMouseClicked
                               

                         
        private void tambahData(){
        String id = txt_idpegawai.getText();
        String nama = txt_namapegawai.getText();
        String alamat = txt_alamat.getText();
        String nohp = txt_no_hp.getText();
        String jenis = cb_pegawai.getSelectedItem().toString();
        String jeniskel = cb_jeniskelamin.getSelectedItem().toString();
        
        //panggil koneksi
        Connection connect = Koneksi.Koneksi.getKoneksi();
        //query untuk memasukan data
        String query = "INSERT INTO `t_pegawai` (id_pegawai, `nama_pegawai`,`jenis_kelamin`,`jenis_pegawai`,`alamat`, `no_hp`) "
                     + "VALUES ('"+id+"', '"+nama+"','"+jeniskel+"','"+jenis+"','"+alamat+"', '"+nohp+"')";
        String query2 = "INSERT INTO `t_users` (id_user, `username`,`password`, `hakakses`) "
                     + "VALUES ('"+id+"', '"+nama+"','"+nama+"', '"+jenis+"')";
        
        try{
            //menyiapkan statement untuk di eksekusi
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.executeUpdate(query);
            PreparedStatement ps2 = (PreparedStatement) connect.prepareStatement(query2);
            ps.executeUpdate(query2);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
            
        }finally{
            tampilData();
            clear();       
        }
    }
    private void clear(){
//        txt_kodebarang.setText(null);
        txt_namapegawai.setText(null);
        txt_alamat.setText(null);
        txt_no_hp.setText(null);
//        txt_tanggal.setDate(null);
        
    }
    private void cari(){
        int row = tabel_pegawai.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String cari = txt_cari.getText();
        
        String query = "SELECT * FROM `t_pegawai` WHERE `id_pegawai`  LIKE '%"+cari+"%' OR `nama_pegawai` LIKE '%"+cari+"%' ";
                
       try{
           Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String id = rslt.getString("id_pegawai");
                    String nama = rslt.getString("nama_pegawai");
                    String jeniskel = rslt.getString("jenis_kelamin");
                    String alamat = rslt.getString("alamat");
                    String nohp = rslt.getString("no_hp");
                    
                    
                //masukan semua data kedalam array
                String[] data = {id,nama,jeniskel,alamat,nohp};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tabel_pegawai.setModel(table);
           
        
    }catch(Exception e){
           System.out.println(e);
    }
    }
   
    private void kodeotomatis(){
        String query = "SELECT * FROM `t_pegawai` ORDER BY id_pegawai DESC ";
        String kodeotomatis;
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String id_pegawai = rslt.getString("id_pegawai").substring(1);
                String AN = "" + (Integer.parseInt(id_pegawai)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                txt_idpegawai.setText("P" + NOL + AN);
            }else{
                txt_idpegawai.setText("P0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.Koneksi.getKoneksi();
        int baris = tabel_pegawai.getSelectedRow();
        int jawab;
        String id = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM `t_pegawai` WHERE `t_pegawai`.`id_pegawai` = '"+id+"';";
        String query2 = "DELETE FROM `t_users` WHERE `t_users`.`id_user` = '"+id+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            PreparedStatement ps2 = (PreparedStatement) connect.prepareStatement(query2);
            ps2.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
            clear();
        }
        
    }
    private void editData(){
        int i = tabel_pegawai.getSelectedRow();
        
        String id = table.getValueAt(i, 0).toString();
        String nama = txt_namapegawai.getText();
        String jeniskel = cb_jeniskelamin.getSelectedItem().toString();
        String jenis = cb_pegawai.getSelectedItem().toString();
        String alamat = txt_alamat.getText();
        String nohp = txt_no_hp.getText();
        
        
        Connection connect = Koneksi.Koneksi.getKoneksi();
        
        String query = "UPDATE `t_pegawai` SET `nama_pegawai` = '"+nama+"',`jenis_kelamin` = '"+jeniskel+"',`jenis_pegawai` = '"+jenis+"', `alamat` = '"+alamat+"', `no_hp` = '"+nohp+"' "
                + "WHERE `t_pegawai`.`id_pegawai` = '"+id+"';";
        String query2 = "UPDATE `t_users` SET `username` = '"+nama+"',`password` = '"+nama+"', `hakakses` = '"+jenis+"' "
                + "WHERE `t_users`.`id_user` = '"+id+"';";

        try{
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.executeUpdate(query);
            PreparedStatement ps2 = (PreparedStatement) connect.prepareStatement(query2);
            ps.executeUpdate(query2);
            JOptionPane.showMessageDialog(null , "Data Update");
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal Update");
        }finally{
            tampilData();
            clear();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JComboBox<String> cb_jeniskelamin;
    private javax.swing.JComboBox<String> cb_pegawai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pegawai;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_idpegawai;
    private javax.swing.JTextField txt_namapegawai;
    private javax.swing.JTextField txt_no_hp;
    // End of variables declaration//GEN-END:variables
}
